#Data Base Configuration
spring:  datasource:    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: system
    password: system
---
#Hibernate Data Properties
spring:  jpa:
    show-sql: true    hibernate:      ddl-auto: update